/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2edd;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Interfaz del programa. 
 * @author 
 */
public class Interfaz extends javax.swing.JFrame {
    
    HashTable info = new HashTable(301);
    HashAlt pClave = new HashAlt(301);
    HashAlt auth = new HashAlt(301);
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * Deja al usuario elegir un archivo, a partir del cual se extraerá la información.
     * @param entrada
     * @param entradaAut
     * @param entradaClav
     * @return 
     */
    public String agregar_Resumen(HashTable entrada, HashAlt entradaAut, HashAlt entradaClav){
            String txt;
            String auxTitulo = "";    
            String auxAutor = "";
            String auxResumen = "";
            String auxPClave = "";
            try{
                JFileChooser elegir_archivo = new JFileChooser();
                elegir_archivo.showOpenDialog(this);
                File archivo_elegido = elegir_archivo.getSelectedFile();
                if (archivo_elegido==null){
                    return "Ningún archivo fue elegido";
                }
                else{
                    FileReader archivo=new FileReader(archivo_elegido);
                    BufferedReader leer=new BufferedReader(archivo);
                    while(!(txt=leer.readLine()).equals("Autores")){
                        auxTitulo += txt + " ";
                    }                   
                    while(!(txt=leer.readLine()).equals("Resumen")){
                        auxAutor += txt + ", ";
                    }
                    while(!(txt=leer.readLine()).equals("")){
                        auxResumen += txt + " ";
                    }
                    while((txt=leer.readLine())!=null){
                        auxPClave += txt + ", ";
                    }
                    String[] x = auxAutor.split(", ");
                    String[] y = auxPClave.split(", ");
                    y[0] = y[0].replace("Palabras Claves: ", "");
                    y[y.length-1] = y[y.length-1].replace(".", "");

                    if(entrada.buscar(auxTitulo)==null){
                    Elementos_Hash elem = new Elementos_Hash(auxTitulo, x, auxResumen, y);
                  
                    for(int i= 0; i<x.length; i++){
                        ElementosHalt autores = new ElementosHalt(x[i], auxTitulo);
                            entradaAut.insertar(autores);
                    }
                    for(int i= 0; i<y.length; i++){
                        ElementosHalt palabras_clave = new ElementosHalt(y[i], auxTitulo);
                            entradaClav.insertar(palabras_clave);
                    }
                    
                    entrada.insertar(elem);
                    
                    }
                    else{
                        return "El resumen ya existe, por favor seleccione otro resumen para añadir";
                    }
                }     
        }catch(Exception e){
        return "Ha ocurrido un error";
        }
        return "Se ha leído el archivo";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Agregar Resumen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, agregar_Resumen(info, auth, pClave));
        ElementosHalt x = new ElementosHalt("ingeniería de dominio", null);
        System.out.println(pClave.get_index(x));
        System.out.println(pClave.buscar(x).getKey());
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
